#cloud-config
runcmd:
  - touch /test.txt
  - apt-get update
  - apt-get install -y curl git wget
  - snap install docker
  - git clone https://github.com/ThomasDeboel/StockExchange.git
  - cd StockExchange/stonks
  - docker compose build
  - docker compose up -d
